### ISSUE TITLE
Wrong distances since 0.21

### ISSUE THREAD

**Issue by eserte** [bluefeet/Geo-Distance#15]
With 0.21 and 0.22 distances calculcated by Geo::Distance seem to be wrong. A test script, which uses Geo::Distance and Math::Trig for caculating a distance:
```
#!/usr/bin/env perl

use strict;
use warnings;
use Geo::Distance;
use Math::Trig;

my $lon0 = 13.385900;
my $lat0 = 52.484977;
my $lon1 = 13.370897;
my $lat1 = 52.485033;

my $geo = Geo::Distance->new;
print "Geo::Distance $Geo::Distance::VERSION: ", $geo->distance('meter', $lon0,$lat0,$lon1,$lat1), "\n";

{
    my $lon0 = Math::Trig::deg2rad($lon0);
    my $lat0 = Math::Trig::deg2rad(90 - $lat0);
    my $lon1 = Math::Trig::deg2rad($lon1);
    my $lat1 = Math::Trig::deg2rad(90 - $lat1);
    print "Math::Trig: ", Math::Trig::great_circle_distance($lon0, $lat0,
							    $lon1, $lat1, 6372795), "\n";

}

__END__
```
With Geo::Distance 0.20 the output looks fine:
```
Geo::Distance 0.20: 1016.03829356047
Math::Trig: 1016.22247060106
```
Since 0.21 the distance is quite off:
```
Geo::Distance 0.21: 1668.43606971801
Math::Trig: 1016.22247060106
```

**Comment by bluefeet** [comment]
Ouch!  😳  Fixing...

**Comment by bluefeet** [comment]
This is resolved in 8ceb20d58636d7406c96beeb279dc9af59ba6228.

I'll be releasing Geo::Distance 0.23 shortly with the fix.

**Comment by bluefeet** [comment]
OK, 0.23 should be out on your local CPAN mirror soon.  Could you take a look and see if it resolves all your issues?

**Comment by eserte** [comment]
Yes --- my previously failing test suite is happy now.
