### ISSUE TITLE
Geo::Distance 0.22 breaks DERF/Travel-Status-DE-IRIS-1.24.tar.gz

### ISSUE THREAD

**Issue by eserte** [bluefeet/Geo-Distance#17]
Another victim of Geo::Distance 0.22 (and possibly 0.21) (@derf: FYI):
```
#   Failed test 'get_station_by_location: 10 matches for Foobar'
#   at t/21-iris-stations.t line 86.
#     Structures begin differing at:
#          $got->[1][0] = 'EESA'
#     $expected->[1][0] = 'EE'

#   Failed test 'get_station_by_location(Foobar): correct distance'
#   at t/21-iris-stations.t line 111.
# 0.1808642 and 0.1272343 are not equal to within 0.000001
# Looks like you failed 2 tests of 17.
t/21-iris-stations.t .... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/17 subtests 
```

Statistical analysis so far:
```
****************************************************************
Regression 'mod:Geo::Distance'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      1.0000	      0.0000	326841869299229888.00
[1='eq_0.22']  	     -1.0000	      0.0000	-85538426647660416.00

R^2= 1.000, N= 73, K= 2
****************************************************************
```

**Comment by bluefeet** [comment]
The fix for #15 should resolve this.

**Comment by eserte** [comment]
I don't see any failures anymore if using 0.23.

**Comment by eserte** [comment]
Just for reference: the test suite of GWILLIAMS/RDF-Query-2.918 was also affected, it seems (@kasei: FYI). An example fail report: http://www.cpantesters.org/cpan/report/299de2be-41c5-11e9-98d7-ea1e1f24ea8f . I cannot tell for sure, as Geo::Distance is only an optional dependency and not listed in RDF-Query's metadata, and thus not available for statistical analysis.

**Comment by kasei** [comment]
@eserte Thanks for the ping. RDF::Query is indeed affected by this. I'll add an explicit `recommends` dependency for v0.23.
